version: '2'
services:
  api:
    build: .
    image: warmans/stressfaktor-api:0.11.0
    volumes:
      - "/var/lib/stressfaktor-api:/var/lib/stressfaktor-api"
      - "/var/log/stressfaktor-api:/var/log/stressfaktor-api"
    restart: always
    ports:
      - "8081:8080"
    expose:
      - "8080"
    environment:
      SERVER_ENCRYPTION_KEY: changeme912345678901234567812312